const config = window.NEXORA_CONFIG || {};
const AGORA_SERVER = window.location.origin;
const AGORA_CHANNEL = `nexora-${crypto.randomUUID().replaceAll('-', '').slice(0, 20)}`;
const AGORA_UID = Math.floor(Math.random() * 1_000_000) + 1;
let agoraClient = null, microphoneTrack = null, agoraAgentId = null, isConnectingAgora = false;
const chat = document.querySelector('#chat'), form = document.querySelector('#chatForm'), input = document.querySelector('#promptInput'), voiceButton = document.querySelector('#voiceButton'), statusText = document.querySelector('#statusText'), history = [];
function addMessage(content, role = 'assistant', extra = '') { const message = document.createElement('article'); message.className = `message ${role} ${extra}`; message.innerHTML = role === 'assistant' ? '<div class="avatar">N</div><div class="bubble"></div>' : '<div class="bubble"></div>'; message.querySelector('.bubble').textContent = content; chat.append(message); message.scrollIntoView({behavior: 'smooth', block: 'end'}); return message; }
async function getReply(prompt) { if (!config.endpoint) return `I’m in demo mode. Connect your endpoint in api-config.js to send: “${prompt}”.`; const response = await fetch(config.endpoint, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({model: config.model, messages: [...history, {role: 'user', content: prompt}]})}); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Your AI endpoint returned an error.'); return data.reply || data.message || data.choices?.[0]?.message?.content || 'Your endpoint returned no reply.'; }
form.addEventListener('submit', async event => { event.preventDefault(); const prompt = input.value.trim(); if (!prompt) return; addMessage(prompt, 'user'); history.push({role: 'user', content: prompt}); input.value = ''; input.style.height = 'auto'; const pending = addMessage('Thinking', 'assistant', 'thinking'); statusText.textContent = 'Nexora is thinking'; try { const reply = await getReply(prompt); pending.remove(); addMessage(reply); history.push({role: 'assistant', content: reply}); } catch (error) { pending.remove(); addMessage(error.message || 'Something went wrong. Please try again.'); } if (!agoraClient) statusText.textContent = 'Ready to assist'; });
input.addEventListener('input', () => { input.style.height = 'auto'; input.style.height = `${Math.min(input.scrollHeight, 130)}px`; }); document.querySelectorAll('.suggestion').forEach(button => button.addEventListener('click', () => { input.value = button.textContent; input.focus(); }));
function setVoiceButton(live) { voiceButton.classList.toggle('listening', live); voiceButton.setAttribute('aria-label', live ? 'End voice conversation' : 'Start voice conversation'); voiceButton.title = live ? 'End voice conversation' : 'Start voice conversation'; }
async function getJson(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'The server returned an error.'); return data; }
async function playRemoteAudio(user, mediaType) { await agoraClient.subscribe(user, mediaType); if (mediaType === 'audio') user.audioTrack.play(); }
async function connectAgora() { if (isConnectingAgora || agoraClient) return; isConnectingAgora = true; voiceButton.disabled = true; try { statusText.textContent = 'Connecting voice conversation…'; const tokenData = await getJson(`${AGORA_SERVER}/agora/token?channel=${encodeURIComponent(AGORA_CHANNEL)}&uid=${AGORA_UID}`); agoraClient = AgoraRTC.createClient({mode: 'rtc', codec: 'vp8'}); agoraClient.on('user-published', playRemoteAudio); agoraClient.on('user-unpublished', (user, mediaType) => { if (mediaType === 'audio') user.audioTrack?.stop(); }); await agoraClient.join(tokenData.appId, tokenData.channel, tokenData.token, tokenData.uid); microphoneTrack = await AgoraRTC.createMicrophoneAudioTrack(); await agoraClient.publish([microphoneTrack]); const agentResult = await getJson(`${AGORA_SERVER}/api/ai/start`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({channel: tokenData.channel, uid: tokenData.uid})}); agoraAgentId = agentResult.agent?.agent_id || agentResult.agent?.agentId; if (!agoraAgentId) throw new Error('Agora started an agent but did not return its ID.'); setVoiceButton(true); statusText.textContent = 'Voice conversation is live'; } catch (error) { console.error('Agora connection error:', error); statusText.textContent = `Voice connection failed: ${error.message}`; await disconnectAgora(false); } finally { isConnectingAgora = false; voiceButton.disabled = false; } }
async function disconnectAgora(stopAgent = true) { const agentId = agoraAgentId; agoraAgentId = null; if (stopAgent && agentId) { try { await getJson(`${AGORA_SERVER}/api/ai/stop`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({agentId})}); } catch (error) { console.warn('Could not stop Agora agent:', error); } } if (microphoneTrack) { microphoneTrack.stop(); microphoneTrack.close(); microphoneTrack = null; } if (agoraClient) { try { await agoraClient.leave(); } catch (error) { console.warn('Could not leave Agora channel:', error); } agoraClient.removeAllListeners(); agoraClient = null; } setVoiceButton(false); if (!isConnectingAgora) statusText.textContent = 'Ready to assist'; }
voiceButton.addEventListener('click', () => agoraClient ? disconnectAgora() : connectAgora());
window.addEventListener('beforeunload', () => { microphoneTrack?.close(); agoraClient?.leave(); });
